# --- Site basics -------------------------------------------------------------
title: "Siegfried Kaltmann"
tagline: "Notizen, Code & Projekte"
description: "HTL - Maschinenbau, Programmierung und Hobbies."
lang: de
timezone: Europe/Vienna
future: true

# --- URLs (Projekt-Seite) ----------------------------------------------------
url: "https://siegikaltmann.github.io"
baseurl: "/blog-with-chirpy"   # -> https://siegikaltmann.github.io/blog-with-chirpy/...

# --- Theme -------------------------------------------------------------------
theme: jekyll-theme-chirpy
theme_mode: light

# --- Social ------------------------------------------------------------------
github:
  username: siegikaltmann
social:
  name: Siegfried Kaltmann
  email: siegfriedkaltmann@gmail.com
  links:
    - https://github.com/siegikaltmann

# --- Analytics & Pageviews ---------------------------------------------------
analytics: {}
pageviews:
  provider:

# --- Assets / Avatar / Preview -----------------------------------------------
avatar: /assets/img/avatar.png
social_preview_image:

# --- PWA ---------------------------------------------------------------------
pwa:
  enabled: false
  cache:
    enabled: false

# --- Pagination ---------------------------------------------------------------
paginate: 10
paginate_path: "/page:num"   # /page2, /page3, ...

# --- Markdown / Rouge --------------------------------------------------------
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# --- Collections / Defaults (Chirpy Standard) --------------------------------
collections:
  tabs:
    output: true
    sort_by: order
  docs:                # ← NEU
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:            # ← NEU: Standardwerte für _docs
      path: ""
      type: docs
    values:
      layout: post     # nutzt das schöne Post-Layout von Chirpy
      toc: true
      comments: false
      math: true
      mermaid: true
      # permalink kommt aus der Collection (/docs/:path/)

# --- HTML compress ------------------------------------------------------------
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# --- Archives (aktiv, da Plugin genutzt) -------------------------------------
jekyll-archives:
  enabled: [categories, tags]
  collections: [posts, docs]   # ← NEU: auch _docs in Archiven berücksichtigen
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# --- Plugins (für Actions-Build) ---------------------------------------------
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# --- Excludes ----------------------------------------------------------------
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
