# --- Site basics -------------------------------------------------------------
title: "Siegfried Kaltmann"
tagline: "Notizen, Code & Projekte"
description: "HTL-Ingenieur, Lehrer und Entwickler – Technik, Programmierung und Wissenschaft."
lang: de
timezone: Europe/Vienna

# --- URLs (Projekt-Seite) ----------------------------------------------------
url: "https://siegikaltmann.github.io
baseurl: "/blog-with-chirpy"

# --- Theme -------------------------------------------------------------------
theme: jekyll-theme-chirpy
theme_mode: light

# --- Social ------------------------------------------------------------------
github:
  username: siegikaltmann
social:
  name: Siegfried Kaltmann
  email: siegikaltmann@gmail.com
  links:
    - https://github.com/siegikaltmann

# --- Analytics & Pageviews (leer lassen) -------------------------------------
analytics: {}
pageviews:
  provider:

# --- Assets / Avatar / Preview -----------------------------------------------
avatar: /assets/img/avatar.png
social_preview_image:

# --- PWA (erstmal aus, damit Favicons kein Build brechen) --------------------
pwa:
  enabled: false
  cache:
    enabled: false

# --- Pagination ---------------------------------------------------------------
paginate: 10

# --- Markdown / Rouge --------------------------------------------------------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# --- Collections / Defaults (Chirpy Standard) --------------------------------
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# --- HTML compress (Standard) ------------------------------------------------
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# --- Archives (Chirpy) -------------------------------------------------------
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# --- Excludes ----------------------------------------------------------------
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
