# --- Site basics -------------------------------------------------------------
title: "Siegfried Kaltmann"
tagline: "Notizen, Code & Projekte"
description: "HTL - Maschinenbau, Programmierung und Hobbies."
lang: de
timezone: Europe/Vienna
future: true

# --- URLs (Projekt-Seite) ----------------------------------------------------
url: "https://siegikaltmann.github.io"
baseurl: "/blog-with-chirpy"

# --- Theme -------------------------------------------------------------------
# Variante A (Build via GitHub Actions/Gemfile):
theme: jekyll-theme-chirpy
# Variante B (wenn GitHub Pages den Build übernimmt):
# remote_theme: cotes2020/jekyll-theme-chirpy

theme_mode: auto

# --- Social ------------------------------------------------------------------
github:
  username: siegikaltmann
social:
  name: Siegfried Kaltmann
  email: siegfriedkaltmann@gmail.com
  links:
    - https://github.com/siegikaltmann

# --- Analytics & Pageviews ---------------------------------------------------
# (beides aus, einfach leer lassen oder entfernen)
analytics: {}
pageviews: {}

# --- Assets / Avatar / Preview -----------------------------------------------
avatar: /assets/img/avatar.png
# alternativ: avatar: assets/img/avatar.png   # (relative ist auch ok)
social_preview_image:


# --- PWA ---------------------------------------------------------------------
pwa:
  enabled: false
  cache:
    enabled: false

# --- Pagination ---------------------------------------------------------------
paginate: 10
paginate_path: "/page:num"

# --- Markdown / Kramdown / Rouge ---------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  math_engine: mathjax
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# --- Collections / Defaults ---------------------------------------------------
collections:
  tabs:
    output: true
    sort_by: order
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
      math: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: ""
      type: docs
    values:
      layout: post
      toc: true
      comments: false
      math: true
      mermaid: true

# --- HTML compress ------------------------------------------------------------
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
# --- Archives -----------------------------------------------------------------
jekyll-archives:
  enabled:
    - categories
    - tags
  collections:
    - posts
    - docs
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

